In [10]:
import numpy as np

In [11]:
import pandas as pd

In [20]:
dfcandidate=pd.read_csv('/Users/mylaramnanditha/Downloads/Candidate Eval Data - for Data Engg Training - Tracker for DE.csv')

In [21]:
dfcandidate

,Name,UID,Email address,OOPS-21,Javascript-14,Cordova-4,Database-4,Testing-12,Analytical-5,Comprehensive-5,Total,Status,Reference,Experience,Role (QA/DEV/DM/Intern),Date of test,Date of eval
0,Hemadri p,1,1@xyz.com,10.0,6.0,0.0,3.0,3.0,0.0,3.0,24/65,Reject,Handigital,3.3yrs,Dev,11/18/2016,11/21/0206
1,Namita Panday,2,2@xyz.com,12.0,7.0,0.0,3.0,9.0,4.0,3.0,37/65,Drop,Otherside consulting,3yrs,QA,11/19/2016,1/21/2016
2,PRADYUMNA KUMAR SAHOO,3,3@xyz.com,9.0,5.0,2.0,2.0,6.0,0.0,0.0,24/65,Reject,Handigital,4.2yrs,Dev,11/18/2016,1/21/2016
3,Md Habibullah Ansari,4,4@xyz.com,12.0,7.0,0.0,2.0,8.0,3.0,2.0,33/65,Reject,otherside consulting,1yr,Dev,11/17/2016,11/17/2016
4,Saurav Singh Sikarwar,5,5@xyz.com,10.0,1.0,1.0,3.0,11.0,2.0,1.0,29/65,Reject,otherside consulting,2.4yrs,QA,11/17/2016,11/17/2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,Vithobanna KS,271,271@xyz.com,11.0,9.0,3.0,4.0,8.0,2.0,1.0,38/65,Open,Talent Cloud,5.11,NaN,NaN,NaN
271,Shanu Shrivastava,272,272@xyz.com,11.0,7.0,0.0,3.0,8.0,5.0,2.0,36/65,Open,Talent Cloud,1.3,NaN,NaN,NaN
272,Fiyaz Ahmed Khan,273,273@xyz.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,Nidhishree,274,274@xyz.com,11.0,7.0,3.0,2.0,6.0,0.0,0.0,29/65,NaN,Srinidhi,1.9yrs,NaN,NaN,NaN
274,Gaurav Upadhyay,275,275@xyz.com,14.0,8.0,0.0,4.0,4.0,2.0,2.0,34/65,Open,appsource,2.8yrs,NaN,NaN,NaN